# Generated by Django 5.0.6 on 2024-06-17 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BINA_Q_notes', '0003_alter_note_tags_noteresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteresponse',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_responses', to='BINA_Q_notes.note'),
        ),
    ]
